### PR TITLE
fix: replaced bad unicode sequence `u+00a0` by space

### PR DESCRIPTION
**Pull request by theobori**

### CODE REVIEW

**Comment by ScriptSathi** [comment]
This error is still present
To give more context, this is the error output (sorry for the french output though)

```
nysm.c: Dans la fonction « main »:
nysm.c:221:27: erreur: « \302 » égaré dans le programme
  221 |     if (arguments.verbose)<U+00A0>{
      |                           ^~~~~~~~
nysm.c:230:27: erreur: « \302 » égaré dans le programme
  230 |     if (arguments.verbose)<U+00A0>{
      |                           ^~~~~~~~
nysm.c:238:31: erreur: « \302 » égaré dans le programme
  238 |         if (arguments.verbose)<U+00A0>{
      |                               ^~~~~~~~
nysm.c:244:31: erreur: « \302 » égaré dans le programme
  244 |         if (arguments.verbose)<U+00A0>{
      |                               ^~~~~~~~
nysm.c:250:27: erreur: « \302 » égaré dans le programme
  250 |     if (arguments.verbose)<U+00A0>{
```

**Comment by theobori** [comment]
Are you sure you used the version with spaces?
It's weird, I checked and I no longer have the error 🤔.

**Comment by ScriptSathi** [comment]
Yep there are no pushed commits to fix this.

I've `git clone` again to take a look, but I again have the error.

```bash
git clone --recursive https://github.com/eeriedusk/nysm.git
cd nysm/libbpf/src
make
 cd ../../src
bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
make

# ...
# nysm.c: Dans la fonction « main »:
# nysm.c:221:27: erreur: « \302 » égaré dans le programme
 #  221 |     if (arguments.verbose)<U+00A0>{
```

**Comment by Koshizo-dev** [comment]
> Yep there are no pushed commits to fix this.
> 
> I've `git clone` again to take a look, but I again have the error.
> 
> ```shell
> git clone --recursive https://github.com/eeriedusk/nysm.git

@ScriptSathi Can you try again, but this time by cloning @theobori 's version ?

`git clone --recursive https://github.com/theobori/nysm.git`

Tell me how it goes.

**Comment by ScriptSathi** [comment]
I do not care if this fork fix the problem ^^
It needed to be pushed on the main repo to be fixed. This is why i'm posting comments

**Comment by eeriedusk** [comment]
Hi! Sorry for the delay, thanks @theobori for the PR! It should be fixed.

**Pull request merged**
